config/routes.rb
LunchTracker::Application.routes.draw do
  resources :lunches

  

end

app/models/lunch.rb
class Lunch < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  before_action :set_lunch, only: [:show, :edit, :update, :destroy]

  # GET /lunches
  # GET /lunches.json
  def index
    @lunches = Lunch.all
  end

  # GET /lunches/1
  # GET /lunches/1.json
  def show
  end

  # GET /lunches/new
  def new
    @lunch = Lunch.new
  end

  # GET /lunches/1/edit
  def edit
  end

  # POST /lunches
  # POST /lunches.json
  def create
    @lunch = Lunch.new(lunch_params)

    respond_to do |format|
      if @lunch.save
        format.html { redirect_to @lunch, notice: 'Lunch was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lunch }
      else
        format.html { render action: 'new' }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lunches/1
  # PATCH/PUT /lunches/1.json
  def update
    respond_to do |format|
      if @lunch.update(lunch_params)
        format.html { redirect_to @lunch, notice: 'Lunch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lunches/1
  # DELETE /lunches/1.json
  def destroy
    @lunch.destroy
    respond_to do |format|
      format.html { redirect_to lunches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lunch
      @lunch = Lunch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lunch_params
      params.require(:lunch).permit(:date, :cost, :calories, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LunchTracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lunches/_form.html.erb
<%= form_for(@lunch) do |f| %>
  <% if @lunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lunch.errors.count, "error") %> prohibited this lunch from being saved:</h2>

      <ul>
      <% @lunch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.text_field :calories %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lunches/edit.html.erb
<h1>Editing lunch</h1>

<%= render 'form' %>

<%= link_to 'Show', @lunch %> |
<%= link_to 'Back', lunches_path %>

app/views/lunches/index.html.erb
<h1>Listing lunches</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Cost</th>
      <th>Calories</th>
      <th>Rating</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lunches.each do |lunch| %>
      <tr>
        <td><%= lunch.date %></td>
        <td><%= lunch.cost %></td>
        <td><%= lunch.calories %></td>
        <td><%= lunch.rating %></td>
        <td><%= link_to 'Show', lunch %></td>
        <td><%= link_to 'Edit', edit_lunch_path(lunch) %></td>
        <td><%= link_to 'Destroy', lunch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lunch', new_lunch_path %>

app/views/lunches/new.html.erb
<h1>New lunch</h1>

<%= render 'form' %>

<%= link_to 'Back', lunches_path %>

app/views/lunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @lunch.date %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @lunch.cost %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @lunch.calories %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @lunch.rating %>
</p>

<%= link_to 'Edit', edit_lunch_path(@lunch) %> |
<%= link_to 'Back', lunches_path %>